import { useState } from 'react';
import { Text, View } from 'react-native';
import { router } from 'expo-router';
import { registerDoctor, ApiError } from '../../src/api';
import { Button, InlineError } from '../../src/ui';
import { AuthCard, AuthField, AuthHeading, AuthScreen, PasswordField, SelectField } from '../../src/auth-ui';
import { colors } from '../../src/theme';

const categories = [{ value: 'PSYCHIATRIST', label: 'Psychiatrist' }, { value: 'PSYCHOLOGIST', label: 'Psychologist' }, { value: 'COUNSELLOR', label: 'Counsellor' }] as const;
const genders = [{ value: 'FEMALE', label: 'Female' }, { value: 'MALE', label: 'Male' }, { value: 'NON_BINARY', label: 'Non-binary' }, { value: 'OTHER', label: 'Other' }, { value: 'PREFER_NOT_TO_SAY', label: 'Prefer not to say' }] as const;
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; const namePattern = /^[A-Za-z][A-Za-z '-]{1,99}$/; const indiaPhonePattern = /^\+91[6-9]\d{9}$/; const licensePattern = /^[A-Za-z0-9][A-Za-z0-9/\- ]{2,99}$/;
type Form = { firstName: string; lastName: string; email: string; password: string; phoneNumber: string; dateOfBirth: string; gender: string; licenseNumber: string; professionalCategory: string; };
type Errors = Partial<Record<keyof Form, string>>;
function validate(form: Form): Errors { const errors: Errors = {}; const birth = new Date(`${form.dateOfBirth}T00:00:00.000Z`); const cutoff = new Date(); cutoff.setUTCFullYear(cutoff.getUTCFullYear() - 18); if (!namePattern.test(form.firstName.trim())) errors.firstName = 'Use at least two letters. Numbers and symbols are not allowed.'; if (!namePattern.test(form.lastName.trim())) errors.lastName = 'Use at least two letters. Numbers and symbols are not allowed.'; if (!emailPattern.test(form.email.trim())) errors.email = 'Enter a valid email address.'; if (form.password.length < 10 || !/[a-z]/.test(form.password) || !/[A-Z]/.test(form.password) || !/\d/.test(form.password)) errors.password = 'Use 10+ characters with uppercase, lowercase, and a number.'; if (!indiaPhonePattern.test(form.phoneNumber.replace(/\s/g, ''))) errors.phoneNumber = 'Use an Indian mobile number, for example +919876543210.'; if (!/^\d{4}-\d{2}-\d{2}$/.test(form.dateOfBirth) || Number.isNaN(birth.getTime()) || birth > cutoff || birth.getUTCFullYear() < 1900) errors.dateOfBirth = 'Use YYYY-MM-DD. You must be at least 18 years old.'; if (!licensePattern.test(form.licenseNumber.trim())) errors.licenseNumber = 'Use at least three letters, numbers, spaces, hyphens, or slashes.'; return errors; }

export function RegisterPanel() {
  const [form, setForm] = useState<Form>({ firstName: '', lastName: '', email: '', password: '', phoneNumber: '+91', dateOfBirth: '', gender: 'PREFER_NOT_TO_SAY', licenseNumber: '', professionalCategory: 'PSYCHOLOGIST' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [errors, setErrors] = useState<Errors>({});
  const set = (key: keyof Form) => (value: string) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })); };
  const submit = async () => { const nextErrors = validate(form); setErrors(nextErrors); setError(''); if (Object.keys(nextErrors).length) { setError('Review the highlighted details before continuing.'); return; } setBusy(true); try { const payload = { ...form, firstName: form.firstName.trim(), lastName: form.lastName.trim(), email: form.email.trim().toLowerCase(), phoneNumber: form.phoneNumber.replace(/\s/g, ''), licenseNumber: form.licenseNumber.trim(), timezone: 'Asia/Kolkata' }; const challenge = await registerDoctor(payload); router.replace({ pathname: '/(auth)/verify', params: { token: challenge.challengeToken, email: challenge.email, purpose: challenge.purpose } }); } catch (caught) { setError((caught as ApiError).message); } finally { setBusy(false); } };
  return <><AuthHeading title="Start your practice" subtitle="Create your account. Email verification and professional approval happen separately." /><AuthCard><View style={{ gap: 3 }}><Text style={{ color: colors.ink, fontWeight: '800', fontSize: 16 }}>Your details</Text><Text style={{ color: colors.muted, fontSize: 12, lineHeight: 17 }}>Use the information that appears on your professional credentials.</Text></View><AuthField label="First name" value={form.firstName} onChangeText={set('firstName')} autoComplete="given-name" placeholder="First name" error={errors.firstName} /><AuthField label="Last name" value={form.lastName} onChangeText={set('lastName')} autoComplete="family-name" placeholder="Last name" error={errors.lastName} /><AuthField label="Email address" autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={form.email} onChangeText={set('email')} placeholder="name@example.com" error={errors.email} /><PasswordField label="Create password" value={form.password} onChangeText={set('password')} autoComplete="new-password" helper="At least 10 characters, including uppercase, lowercase, and a number." error={errors.password} /><AuthField label="Indian mobile number" keyboardType="phone-pad" value={form.phoneNumber} onChangeText={set('phoneNumber')} placeholder="+919876543210" error={errors.phoneNumber} /><AuthField label="Date of birth" keyboardType="numbers-and-punctuation" value={form.dateOfBirth} onChangeText={set('dateOfBirth')} placeholder="YYYY-MM-DD" error={errors.dateOfBirth} /><SelectField label="Gender" value={form.gender} options={genders} onChange={set('gender')} /><SelectField label="Professional category" value={form.professionalCategory} options={categories} onChange={set('professionalCategory')} /><AuthField label="License or registration number" value={form.licenseNumber} onChangeText={set('licenseNumber')} placeholder="Enter your registration number" error={errors.licenseNumber} /><InlineError message={error} /><Button label="Create account and send code" onPress={submit} loading={busy} /></AuthCard><Text style={{ color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' }}>Registration does not approve a professional to take sessions. Your credentials must be reviewed first.</Text></>;
}
export default function Register() { return <AuthScreen mode="register"><RegisterPanel /></AuthScreen>; }
