import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState, type ReactNode } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { colors, shadow } from './theme';

type AuthMode = 'login' | 'register';

export function AuthScreen({ mode, children, onModeChange }: { mode: AuthMode; children: ReactNode; onModeChange?: (mode: AuthMode) => void }) {
  return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={0}>
    <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" automaticallyAdjustKeyboardInsets showsVerticalScrollIndicator={false}>
      <View style={styles.brand} accessibilityRole="header"><View style={styles.logoMark}><Ionicons name="heart" size={25} color="#fff" /></View><Text style={styles.wordmark}>AntarTalk</Text><Text style={styles.professionals}>PROFESSIONALS</Text></View>
      <View style={styles.switcher} accessibilityRole="tablist"><Pressable accessibilityRole="tab" accessibilityState={{ selected: mode === 'login' }} onPress={() => onModeChange ? onModeChange('login') : router.replace('/auth')} style={[styles.switchOption, mode === 'login' && styles.switchOptionActive]}><Text style={[styles.switchText, mode === 'login' && styles.switchTextActive]}>Sign in</Text></Pressable><Pressable accessibilityRole="tab" accessibilityState={{ selected: mode === 'register' }} onPress={() => onModeChange ? onModeChange('register') : router.replace('/auth?mode=register')} style={[styles.switchOption, mode === 'register' && styles.switchOptionActive]}><Text style={[styles.switchText, mode === 'register' && styles.switchTextActive]}>Create account</Text></Pressable></View>
      <View style={styles.content}>{children}</View><Text style={styles.footer}>A private workspace for verified mental-health professionals.</Text>
    </ScrollView>
  </KeyboardAvoidingView>;
}

export function AuthHeading({ title, subtitle }: { title: string; subtitle: string }) { return <View style={styles.heading}><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View>; }
export function AuthCard({ children }: { children: ReactNode }) { return <View style={styles.card}>{children}</View>; }
export function AuthField({ label, helper, error, right, ...props }: TextInputProps & { label: string; helper?: string; error?: string; right?: ReactNode }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={[styles.inputWrap, error && styles.inputWrapError]}><TextInput style={styles.input} placeholderTextColor="#7B8494" {...props} />{right}</View>{error ? <Text style={styles.fieldError}>{error}</Text> : helper ? <Text style={styles.helper}>{helper}</Text> : null}</View>; }
export function PasswordField({ label = 'Password', value, onChangeText, error, helper, autoComplete = 'password' }: { label?: string; value: string; onChangeText: (value: string) => void; error?: string; helper?: string; autoComplete?: TextInputProps['autoComplete'] }) { const [hidden, setHidden] = useState(true); return <AuthField label={label} value={value} onChangeText={onChangeText} error={error} helper={helper} secureTextEntry={hidden} autoComplete={autoComplete} textContentType={autoComplete === 'new-password' ? 'newPassword' : 'password'} right={<Pressable accessibilityRole="button" accessibilityLabel={hidden ? 'Show password' : 'Hide password'} onPress={() => setHidden((current) => !current)} hitSlop={10} style={styles.eye}><Ionicons name={hidden ? 'eye-outline' : 'eye-off-outline'} size={20} color={colors.muted} /></Pressable>} />; }
export function SelectField({ label, value, options, error, onChange }: { label: string; value: string; options: readonly { value: string; label: string }[]; error?: string; onChange: (value: string) => void }) { const [visible, setVisible] = useState(false); const selected = options.find((option) => option.value === value)?.label ?? 'Select an option'; return <View style={styles.field}><Text style={styles.label}>{label}</Text><Pressable onPress={() => setVisible(true)} style={[styles.select, error && styles.inputWrapError]} accessibilityRole="button" accessibilityLabel={`${label}: ${selected}`}><Text style={styles.selectValue}>{selected}</Text><Ionicons name="chevron-down" color={colors.ink} size={19} /></Pressable>{error ? <Text style={styles.fieldError}>{error}</Text> : null}<Modal visible={visible} transparent animationType="fade" onRequestClose={() => setVisible(false)}><Pressable style={styles.modalOverlay} onPress={() => setVisible(false)}><Pressable style={styles.modalSheet} onPress={(event) => event.stopPropagation()}><Text style={styles.modalTitle}>{label}</Text>{options.map((option) => <Pressable key={option.value} onPress={() => { onChange(option.value); setVisible(false); }} style={[styles.option, option.value === value && styles.optionSelected]}><Text style={[styles.optionText, option.value === value && styles.optionTextSelected]}>{option.label}</Text>{option.value === value ? <Ionicons name="checkmark" size={20} color={colors.pink} /> : null}</Pressable>)}</Pressable></Pressable></Modal></View>; }

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background }, scroll: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 42, paddingBottom: 28 }, brand: { alignItems: 'center', marginBottom: 27 }, logoMark: { width: 50, height: 50, borderRadius: 25, backgroundColor: colors.pink, alignItems: 'center', justifyContent: 'center', marginBottom: 9, ...shadow }, wordmark: { color: colors.ink, fontSize: 25, fontWeight: '800', letterSpacing: -0.65 }, professionals: { color: colors.teal, fontSize: 9, fontWeight: '800', letterSpacing: 2.2, marginTop: 3 }, switcher: { backgroundColor: '#F3E9EE', borderRadius: 15, padding: 4, flexDirection: 'row', marginBottom: 25 }, switchOption: { flex: 1, alignItems: 'center', justifyContent: 'center', minHeight: 43, borderRadius: 11 }, switchOptionActive: { backgroundColor: colors.surface, ...shadow }, switchText: { color: colors.muted, fontSize: 14, fontWeight: '700' }, switchTextActive: { color: colors.ink }, content: { gap: 16 }, heading: { gap: 7 }, title: { color: colors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -0.8 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21 }, card: { backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, borderRadius: 20, padding: 18, gap: 15, ...shadow }, field: { gap: 6 }, label: { color: colors.ink, fontWeight: '700', fontSize: 13 }, inputWrap: { minHeight: 50, borderWidth: 1, borderColor: colors.line, borderRadius: 13, paddingLeft: 13, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center' }, inputWrapError: { borderColor: colors.danger, backgroundColor: '#FFF7F9' }, input: { flex: 1, alignSelf: 'stretch', color: colors.ink, fontSize: 16, paddingVertical: 11 }, eye: { paddingHorizontal: 13, minHeight: 48, justifyContent: 'center' }, helper: { color: colors.muted, fontSize: 12, lineHeight: 17 }, fieldError: { color: colors.danger, fontSize: 12, lineHeight: 17, fontWeight: '600' }, select: { minHeight: 50, borderWidth: 1, borderColor: colors.line, borderRadius: 13, paddingHorizontal: 13, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, selectValue: { color: colors.ink, fontSize: 16 }, modalOverlay: { flex: 1, backgroundColor: 'rgba(23, 32, 51, 0.38)', justifyContent: 'flex-end' }, modalSheet: { backgroundColor: '#fff', borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 22, paddingBottom: 36, gap: 5 }, modalTitle: { color: colors.ink, fontSize: 18, fontWeight: '800', marginBottom: 8 }, option: { minHeight: 54, paddingHorizontal: 13, borderRadius: 12, justifyContent: 'space-between', alignItems: 'center', flexDirection: 'row' }, optionSelected: { backgroundColor: colors.pinkSoft }, optionText: { color: colors.ink, fontSize: 16, fontWeight: '600' }, optionTextSelected: { color: colors.pink, fontWeight: '800' }, footer: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 'auto', paddingTop: 28 }
});
