import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, shadow } from './theme';

export function Screen({ children, scroll = true }: { children: React.ReactNode; scroll?: boolean }) { const inner = <View style={styles.screen}>{children}</View>; return scroll ? <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={0}><ScrollView style={styles.root} contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" automaticallyAdjustKeyboardInsets>{inner}</ScrollView></KeyboardAvoidingView> : <View style={[styles.root, styles.screen]}>{children}</View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: ViewStyle }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Title({ children, subtitle }: { children: string; subtitle?: string }) { return <View style={styles.titleWrap}><Text style={styles.title}>{children}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>; }
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor="#98A0AE" style={styles.input} {...props} /></View>; }
export function Button({ label, onPress, loading, variant = 'primary', disabled }: { label: string; onPress: () => void; loading?: boolean; disabled?: boolean; variant?: 'primary' | 'secondary' | 'danger' }) { const tone = variant === 'secondary' ? styles.secondaryButton : variant === 'danger' ? styles.dangerButton : styles.primaryButton; return <Pressable onPress={onPress} disabled={loading || disabled} style={({ pressed }) => [styles.button, tone, (loading || disabled) && styles.disabled, pressed && styles.pressed]}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={[styles.buttonLabel, variant === 'secondary' && styles.secondaryButtonLabel]}>{label}</Text>}</Pressable>; }
export function InlineError({ message, retry }: { message?: string; retry?: () => void }) { if (!message) return null; return <View style={styles.error}><Ionicons name="alert-circle-outline" size={18} color={colors.danger} /><View style={{ flex: 1 }}><Text style={styles.errorText}>{message}</Text>{retry ? <Pressable onPress={retry}><Text style={styles.retry}>Retry</Text></Pressable> : null}</View></View>; }
export function Loader({ label = 'Loading AntarTalk…' }: { label?: string }) { return <View style={styles.loader}><ActivityIndicator size="large" color={colors.pink} /><Text style={styles.loaderText}>{label}</Text></View>; }
export function confirm(title: string, message: string, action: () => void, destructive = false) { Alert.alert(title, message, [{ text: 'Not now', style: 'cancel' }, { text: 'Continue', style: destructive ? 'destructive' : 'default', onPress: action }]); }
export const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, scroll: { paddingBottom: 34 }, screen: { paddingHorizontal: 20, paddingTop: 18, gap: 14 }, titleWrap: { gap: 5, marginBottom: 4 }, title: { color: colors.ink, fontSize: 27, fontWeight: '700', letterSpacing: -0.6 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 20 }, card: { backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, borderRadius: 18, padding: 16, ...shadow }, field: { gap: 6 }, label: { color: colors.ink, fontSize: 13, fontWeight: '600' }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 12, paddingHorizontal: 13, paddingVertical: 12, color: colors.ink, fontSize: 16, backgroundColor: '#fff' }, button: { minHeight: 48, paddingHorizontal: 18, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginTop: 2 }, primaryButton: { backgroundColor: colors.pink }, secondaryButton: { backgroundColor: colors.surface, borderColor: colors.pink, borderWidth: 1 }, dangerButton: { backgroundColor: colors.danger }, buttonLabel: { color: '#fff', fontWeight: '700', fontSize: 15 }, secondaryButtonLabel: { color: colors.pink }, disabled: { opacity: 0.55 }, pressed: { transform: [{ scale: 0.98 }] }, error: { flexDirection: 'row', gap: 9, borderRadius: 12, backgroundColor: '#FFF0F4', padding: 12 }, errorText: { color: colors.danger, fontSize: 13, lineHeight: 18 }, retry: { color: colors.pink, fontWeight: '700', marginTop: 5 }, loader: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14, backgroundColor: colors.background }, loaderText: { color: colors.muted, fontSize: 14 } });
